config/routes.rb
Rails.application.routes.draw do

  resources :insta_tags
  get 'pages/hello_world'

  root :to => redirect("/pages/hello_world")
end

app/models/insta_tag.rb
class InstaTag < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  # Sad cemo definisemo ruby metodu
  def hello
    render text: "hello, world!"
  end

  # Sada treba da objasnimo Railsu da koristi ovu nasu akciju umesto default strane
  # Da bismo to uradili, editujemo Rails router koji nam je ovde u ulozi dispecera
  # On odredjuje gde treba da se prosledi zahtev koji primi iz browsera
  # Zelimo da promenimo "the root route", koja odredjuje sta se otvara na root URL
  # otvaramo config/routes.rb
end

app/controllers/insta_tags_controller.rb
class InstaTagsController < ApplicationController
  before_action :set_insta_tag, only: [:show, :edit, :update, :destroy]

  # GET /insta_tags
  # GET /insta_tags.json
  def index
    @popular = Instagram.media_popular
  end

  # GET /insta_tags/1
  # GET /insta_tags/1.json
  def show
  end

  # GET /insta_tags/new
  def new
    @insta_tag = InstaTag.new
  end

  # GET /insta_tags/1/edit
  def edit
  end

  # POST /insta_tags
  # POST /insta_tags.json
  def create
    @insta_tag = InstaTag.new(insta_tag_params)

    respond_to do |format|
      if @insta_tag.save
        format.html { redirect_to @insta_tag, notice: 'Insta tag was successfully created.' }
        format.json { render :show, status: :created, location: @insta_tag }
      else
        format.html { render :new }
        format.json { render json: @insta_tag.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /insta_tags/1
  # PATCH/PUT /insta_tags/1.json
  def update
    respond_to do |format|
      if @insta_tag.update(insta_tag_params)
        format.html { redirect_to @insta_tag, notice: 'Insta tag was successfully updated.' }
        format.json { render :show, status: :ok, location: @insta_tag }
      else
        format.html { render :edit }
        format.json { render json: @insta_tag.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /insta_tags/1
  # DELETE /insta_tags/1.json
  def destroy
    @insta_tag.destroy
    respond_to do |format|
      format.html { redirect_to insta_tags_url, notice: 'Insta tag was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_insta_tag
      @insta_tag = InstaTag.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def insta_tag_params
      params.require(:insta_tag).permit(:name)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def hello_world
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/insta_tags_helper.rb
module InstaTagsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/insta_tags/_form.html.erb
<%= form_for(@insta_tag) do |f| %>
  <% if @insta_tag.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@insta_tag.errors.count, "error") %> prohibited this insta_tag from being saved:</h2>

      <ul>
      <% @insta_tag.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/insta_tags/edit.html.erb
<h1>Editing Insta Tag</h1>

<%= render 'form' %>

<%= link_to 'Show', @insta_tag %> |
<%= link_to 'Back', insta_tags_path %>

app/views/insta_tags/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Insta Tags</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @insta_tags.each do |insta_tag| %>
      <tr>
        <td><%= insta_tag.name %></td>
        <td><%= link_to 'Show', insta_tag %></td>
        <td><%= link_to 'Edit', edit_insta_tag_path(insta_tag) %></td>
        <td><%= link_to 'Destroy', insta_tag, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Insta tag', new_insta_tag_path %>

app/views/insta_tags/new.html.erb
<h1>New Insta Tag</h1>

<%= render 'form' %>

<%= link_to 'Back', insta_tags_path %>

app/views/insta_tags/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @insta_tag.name %>
</p>

<%= link_to 'Edit', edit_insta_tag_path(@insta_tag) %> |
<%= link_to 'Back', insta_tags_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
<title>InstagramProba</title>
  <link rel="stylesheet" href="//railsgirls.com/assets/bootstrap.css">
  <link rel="stylesheet" href="//railsgirls.com/assets/bootstrap-theme.css">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <nav class="navbar navbar-default navbar-fixed-top" role="navigation">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="/">Welcome</a>
        </div>
        <div class="collapse navbar-collapse">
          <ul class="nav navbar-nav">
            <li class="active"><a href="/insta_tags">Insta tags</a></li>
          </ul>
        </div>
      </div>
  </nav>

<div class="container">
    <%= yield %>
</div>

  <footer>
    <div class="container">
      Rails Girls 2016
    </div>
  </footer>
  <script src="//railsgirls.com/assets/bootstrap.js"></script>

</body>
</html>

app/views/pages/hello_world.html.erb
<h1>My First Rails Girls app</h1>
  <div>
    <h2>Hypatia</h2>
    <div>
      <p>"Reserve your right to think, for even to think wrongly is better than not to think at all."</p>
      <p>"Life is an unfoldment, and the further we travel the more truth we can comprehend. To understand the things that are at our door is the best preparation for understanding those that lie beyond."</p>
      <img src="http://wp.production.patheos.com/blogs/cosmostheinlost/files/2014/03/hypatiaFCA.jpg" />
    </div>
      <a href="http://www.expecteverything.eu/hypatia">Project</a>
    <h2>HTML</h2>
      <p>To learn more about HTML</p>
      <a href="http://www.w3schools.com/html/">Visit HTML tutorial</a>
    <h2>Find me</h2>
      <a href="https://github.com/mimimalizam">Github</a>
      <a href="https://twitter.com/MStojadinov">Twitter</a>
      <a href="https://www.instagram.com/_mimimum/">Instagram</a>
      <a href="mailto:milana.stojadinov@gmail.com">Send me an email</a>
  </div>